name: CI/CD Pipeline

on:
  push:
    branches: [main]
    tags: ["v*"]

permissions:
  contents: write
  actions: read
  checks: write

concurrency:
  group: cicd-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & Test (main)
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    env:
      ALUVIA_API_KEY: "test_key"
      ALUVIA_MAX_RETRIES: "1"
      ALUVIA_BACKOFF_MS: "50"
      ALUVIA_RETRY_ON: "ETIMEDOUT,net::ERR"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test

      - name: Build package
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  publish:
    name: Publish to npm & Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    env:
      ALUVIA_API_KEY: "test_key"
      ALUVIA_MAX_RETRIES: "1"
      ALUVIA_BACKOFF_MS: "50"
      ALUVIA_RETRY_ON: "ETIMEDOUT,net::ERR"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests (pre-publish gate)
        run: npm test

      - name: Build package
        run: npm run build

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        continue-on-error: true
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## What's Changed

            See [CHANGELOG.md](https://github.com/xtrella/aluvia-playwright/blob/main/CHANGELOG.md) for detailed changes.

            ## Installation

            ```bash
            npm install aluvia-playwright@${{ github.ref_name }}
            ```

            ## Documentation

            Visit our [GitHub repository](https://github.com/xtrella/aluvia-playwright) for complete documentation and examples.
          draft: false
          prerelease: false
